"""Add category_id to transactions

Revision ID: 13c4517bd6a5
Revises: b2c3d4e5f6g7
Create Date: 2025-08-01 04:35:08.883853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c4517bd6a5'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_conversions_user_id'), table_name='currency_conversions')
    op.create_index(op.f('ix_currency_conversions_id'), 'currency_conversions', ['id'], unique=False)
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_id')
    op.drop_index(op.f('ix_currency_conversions_id'), table_name='currency_conversions')
    op.create_index(op.f('ix_currency_conversions_user_id'), 'currency_conversions', ['user_id'], unique=False)
    # ### end Alembic commands ###
