"""Initial migration

Revision ID: 4d2ef3afc9d7
Revises: 
Create Date: 2025-07-15 01:27:05.829798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d2ef3afc9d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS cron CASCADE")
    op.execute("DROP TABLE IF EXISTS thread_ttl CASCADE")
    op.execute("DROP TABLE IF EXISTS charts CASCADE")
    op.execute("DROP TABLE IF EXISTS assistant_versions CASCADE")
    op.execute("DROP TABLE IF EXISTS assistant CASCADE")
    op.execute("DROP TABLE IF EXISTS run CASCADE")
    op.execute("DROP TABLE IF EXISTS thread CASCADE")
    op.execute("DROP TABLE IF EXISTS store CASCADE")
    op.execute("DROP TABLE IF EXISTS schema_migrations CASCADE")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs CASCADE")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes CASCADE")
    op.execute("DROP TABLE IF EXISTS checkpoints CASCADE")

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    # ### end Alembic commands ###