"""Add currency fields to users and create budgets table

Revision ID: 4effc64aa2c3
Revises: 5c54f7a292db
Create Date: 2025-08-01 03:13:12.838391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4effc64aa2c3'
down_revision = '5c54f7a292db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    
    # Add currency columns with default values first
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('currency_symbol', sa.String(), nullable=True))
    
    # Update existing users to have default currency values
    op.execute("UPDATE users SET currency = 'USD', currency_symbol = '$' WHERE currency IS NULL")
    
    # Now make the columns non-nullable
    op.alter_column('users', 'currency', nullable=False)
    op.alter_column('users', 'currency_symbol', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency_symbol')
    op.drop_column('users', 'currency')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
