"""Add user_id to transactions and create categories table

Revision ID: 5c54f7a292db
Revises: fe0c89694888
Create Date: 2025-08-01 00:11:36.343101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54f7a292db'
down_revision = 'fe0c89694888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('budget_limit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_frequency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('transactions', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='date::timestamp')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'recurring_frequency')
    op.drop_column('transactions', 'is_recurring')
    op.drop_column('transactions', 'receipt_url')
    op.drop_column('transactions', 'tags')
    op.drop_column('transactions', 'location')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'user_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
