"""Update User model for Google Auth

Revision ID: fe0c89694888
Revises: 7a7c910c8808
Create Date: 2025-07-15 04:46:17.168213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0c89694888'
down_revision = '7a7c910c8808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
